@startuml
 
namespace score::mw::com {
    interface "SkeletonWrapper<Interface>"  <<interface>> {
      GetTypeErasedElementInfo()
      SetInArgsAndReturnStorages()
      MarkSubscribed()
      MarkUnsubscribed()
    }
}
 
@enduml